spring:
  datasource:
    username: root
    password: Xuxing_2019
    url: jdbc:mysql://192.168.56.10:3306/gulimall_oms?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8090