server:
  port: 30000
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G2Jr8bxFxKKr9aRR9jA
      secret-key: HH8nIkKkbOnyPYNhiR4YR9W9bbnhoc
      oss:
        bucket: xxgulimall
        endpoint: oss-cn-beijing.aliyuncs.com
  application: gulimall-third-party
